<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-11-18T21:11:46Z" name="Suite" finished-at="2024-11-18T21:12:01Z" duration-ms="14516">
    <groups>
    </groups>
    <test started-at="2024-11-18T21:11:46Z" name="Test" finished-at="2024-11-18T21:12:01Z" duration-ms="14516">
      <class name="com.ghate.tests.HomePageTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:com.ghate.tests.HomePageTest@2898ac89]" started-at="2024-11-18T21:11:46Z" name="setup" finished-at="2024-11-18T21:11:57Z" duration-ms="10390" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="TestCase1()[pri:0, instance:com.ghate.tests.HomePageTest@2898ac89]" started-at="2024-11-18T21:11:57Z" name="TestCase1" finished-at="2024-11-18T21:11:58Z" duration-ms="1747" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.ghate.tests.HomePageTest.TestCase1(HomePageTest.java:33)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestCase1 -->
        <test-method is-config="true" signature="tesrDown()[pri:0, instance:com.ghate.tests.HomePageTest@2898ac89]" started-at="2024-11-18T21:11:58Z" name="tesrDown" finished-at="2024-11-18T21:12:01Z" duration-ms="2323" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tesrDown -->
      </class> <!-- com.ghate.tests.HomePageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
